### ISSUE TITLE
Multi-language handling

### ISSUE THREAD

**Issue by emilyb7** [FAC9/backend-badgers-autocomplete#51]
As a user I want to define my preferred language. We should provide situations based on this.

**Comment by njsfield** [comment]
- [x] Node needs to understand formatted text files with special characters. Currently non asci characters are rea but displayed with a ? symbol, which means node cannot filter through the non english text files.
- [x] Options should be visible above/below the input field for user to choose language
- [x] When user clicks language button, get requests fire with the corresponding lang value

**Comment by emilyb7** [comment]
@denesnori i think there may still be some issues with french... i'm getting random numbers when i start typing stuff in...

**Comment by denesnori** [comment]
Ok, I will check it.

**Comment by denesnori** [comment]
I found the bug :). The new dict files have some random things (comments after \t and / signs)...and one of my regular expressions filtering these random staff wasn't working.. :( 
Thanks :). Hopefully it is OK now
