### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by bradreeder** [FAC9/backend-badgers-autocomplete#75]
It looks great! Only some minor adjustments. Bare in mind in telling someone how to run your project locally that they might not necessarily have nodemon installed. If it's necessary to run your project provide instructions on how to install it.

**Comment by bradreeder** [comment]
On that note, looking at your package.json, maybe it would be better to just to tell them to run npm start as that seems to initialise your server?

**Comment by bradreeder** [comment]
You should probably also provide instruction on how to run your tests :-)

**Comment by njsfield** [comment]
Thank you! Will do :)
