### ISSUE TITLE
Return values in main.js

### ISSUE THREAD

**Issue by sofiapoh** [FAC9/backend-badgers-autocomplete#79]
https://github.com/FAC9/backend-badgers-autocomplete/blob/master/public/js/main.js#L122

In your main.js you seem to be sometimes just simply returning and then here returning undefined, is there a specific reason for that? If not, it's better to simply just return for the sake of being more consistent.

**Comment by njsfield** [comment]
Thanks for spotting this! We were trying out different falsey return values to satisfy edge cases in some of our tests, we forgot to remove the unnecessary undefined statements. Pull request to follow...
