### ISSUE TITLE
onclick in html

### ISSUE THREAD

**Issue by bradreeder** [FAC9/backend-badgers-autocomplete#85]
Just quickly reviewed html and it looks good but I noticed you're using onclick on your button elements like this:

```javascript
<button onclick='myFunction() 'class='drop-down-btn'>Language</button>

<button onclick='myLanguage("English")'>English</button>
<button onclick='myLanguage("Danish")'>Danish</button>
<button onclick='myLanguage("Dutch")'>Dutch</button>
```

Your html should only include the content of your app, your css the styles (presentation), and your javascript the behaviour. This way someone reading it knows where all the content is, where the presentation is, and where the behaviour is. Read into separation of concerns.

Don't use onclick in your html instead do something like this in your javascript:

```javascript
var exampleButton = document.getElementById('examplebutton')

var callbackFunction = function() {
  //do something onclick
};

exampleButton.addEventListener('click', callbackFunction);
```

Come find me if you need any help with this. :-)

**Comment by denesnori** [comment]
Done :)
