### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by samhstn** [FAC9/backend-badgers-autocomplete#95]
Really great README badgers,

I love the comments left explaining particular functions, it made reading your code a lot easier

The `router.js` file is really clean too.

I really liked the use of the node api, you used the `path` module really well and made use of lots of its features

**Comment by tbtommyb** [comment]
I really liked the README graphic (and team name).

I thought it was really good that you set out the logic in such detail.

**Comment by tbtommyb** [comment]
Also really like the router.js file.

**Comment by samhstn** [comment]
It looks a little inspired from [somewhere](https://github.com/sofer/sssk)

**Comment by tbtommyb** [comment]
standing on the shoulders of giants

**Comment by Jwhiles** [comment]
genius steals
