### ISSUE TITLE
Language.js

### ISSUE THREAD

**Issue by tbtommyb** [FAC9/backend-badgers-autocomplete#96]
'myFunction' isn't a very useful name for a function.

Although it works, I don't think the function in `window.onclick` is doing what you intended. `options` returns a single div so there is no point doing that loop (`i` never gets above '0'). If `options` were an array you would run into a problem because you need to use a closure to get a local value of `i` for each button (like Elias talked about one day).

You add click handlers to call `myLanguage` with the different languages. You could just give each button a `name` attribute (or something like that) with the two-letter language codes, which you could use within the code (separating how the data is used in the code and how it's presented to the user) and that would save you having to use the `myLanguage` function (the name of this could be more descriptive). There's also no point assigning to a global variable within the function (side effect) and then returning it as well. It would be clearer like `var language = myLanguage(lang)`.

**Comment by denesnori** [comment]
You're right! I removed the useless lines.
