### ISSUE TITLE
Small things in main.js

### ISSUE THREAD

**Issue by tbtommyb** [FAC9/backend-badgers-autocomplete#98]
...that aren't worth their own issues.

Line 127 in the `lastChunk` function you reassign `value` several times. Maybe you could give each new assignment a new, descriptive name each time so that you can see how it's changing.

Line 136 in `filterResults` you don't need to do the check to return an empty array as `filter` will return an empty array if there are no matches. So you can get rid of everything except the function on line 140. Also, the RegExp assignment should be outside the filter loop because it doesn't change on each iteration but you reassign it each time anyway.

**Comment by emilyb7** [comment]
fixed!
